### ISSUE TITLE
Name Tag Still show

### ISSUE THREAD

**Issue by Timty321** [VirgilFabre/NoNameTag#4]
the name tag is still can be see 
i alredy install the plugin : 
https://gyazo.com/7525200775c482553a100dff68485374
at ingame : 
https://gyazo.com/7787b488ed57f7e8d3000e378333fdf2

**Comment by AuracleTech** [comment]
I need the full list of plugins you have installed to try and find which cause the issue in conflict with mine

**Comment by AuracleTech** [comment]
No answer
